### ISSUE TITLE
I have one question regarding defining a keras layer which performs Bilinear tensor product

### ISSUE THREAD

**Issue by WrathofBhuvan11** [palashsharma891/TensorFlow2.0-ImperialCollegeLondon-Coursera#2]
the layer takes 2 vector inputs from previous flatten layers, say e_1 & e_2 which has the shape of (None, 4096) each & I want the bilinear layer to perform (e_1 ⊗ e_2), and thus the resulting output shape be (None, 4096, 4096)

**Comment by palashsharma891** [comment]
What? Can you point where I have used this?

**Comment by WrathofBhuvan11** [comment]
no, it's not there in course. I'm currently doing the Coursera course but alongside that, I'm doing another personal project, & I'm kinda stuck there. So it happens so that I visited your repository. So I just asked.
But I have one ques, are you about to upload all those assignments of all 3 courses ??

**Comment by palashsharma891** [comment]
Not sure bout course 3, but definitely course 2.

**Comment by WrathofBhuvan11** [comment]
Are you about to do Course 3 after Course 2 is done ?

**Comment by palashsharma891** [comment]
Not sure!
